//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GabrielForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projeto_Tarefas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projeto_Tarefas()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int Codigo { get; set; }
        public int CodProjeto { get; set; }
        public string Descricao { get; set; }
        public Nullable<bool> isConcluida { get; set; }
    
        public virtual Projeto Projeto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
